<?php
/**
 * @file
 * Main procedural code for the Mailmute module.
 */

/**
 * Implements hook_mail_alter().
 */
function mailmute_mail_alter(&$message) {
  // @todo Also check Cc, Bcc.
  // The 'to' element is a string, even with multiple recipients.
  // @todo split based on RFC
  // @todo consider all observed formats incl Name <email>
  // @todo if multiple targets and some removed, add header X-Mailmute-To-Remove
  if (\Drupal::service('plugin.manager.sendstate')->isMute($message['to'])) {
    $message['send'] = FALSE;
    drupal_set_message(t('Message to %mail suppressed.', array('%mail' => $message['to'])), 'warning');
  }
}
