<?php
/**
 * @file
 * Main procedural code for the Mailmute module.
 */

/**
 * @mainpage
 * The purpose of the Mailmute module is to suppress all mail sent from the
 * website to certain addresses. The suppression, which happens in
 * mailmute_mail_alter(), is conditional on a so-called sendstate which is
 * defined for each address. The sendstate is implemented as a field on the User
 * entity, with a reference to a plugin defining the actual state.
 *
 *   - @link plugin Sendstate plugins @endlink
 *   - @link field The sendstate field @endlink
 */

/**
 * @defgroup plugin Sendstate plugins
 * @{
 * The states are represented by plugins of the type SendState. This module
 * provides two basic states: Send and On hold. The Send state is selected by
 * default and does not mute, while the On hold state does mute.
 *
 * Being plugins, the states are easily extensible. Other modules may define new
 * states as needed.
 *
 * Every state plugin declares whether it is muting or not (i.e. whether
 * messages to an address in that state should be suppressed). It may also
 * declare other information to contain, as well as provide rendering for
 * display.
 * @}
 */

/**
 * @defgroup field The sendstate field
 * @{
 * The Send State is an entity field that should be present on every entity that
 * represents a receiver of mail. By default, the field is added to the User
 * entity. If you use the Simplenews newsletter module, please additionally
 * enable the mailmute_simplenews submodule, which also adds the field to the
 * Subscriber entity.
 *
 * In theory, a send state is a property of an email address, not a user or
 * subscriber per se. It could be argued that the state should thus be stored
 * separately from the entity, e.g. in a SQL table directly keyed by address. A
 * field-based model is however preferred to leverage the Entity API and to
 * avoid excessive custom schema definitions.
 * @}
 */

/**
 * Implements hook_mail_alter().
 *
 * This hook is where the muting happens. For every outgoing mail it looks up
 * the Send State of the receiving address. If the state is muting, the message
 * is suppressed.
 *
 * Suppression is done by setting $message['send'] to FALSE. Note that this
 * means that it could possibly later be "unsuppressed" by another module.
 */
function mailmute_mail_alter(&$message) {
  // @todo Also check Cc, Bcc.
  // The 'to' element is a string, even with multiple recipients.
  // @todo split based on RFC
  // @todo consider all observed formats incl Name <email>
  // @todo if multiple targets and some removed, add header X-Mailmute-To-Remove
  /** @var \Drupal\mailmute\SendStateManagerInterface $manager */
  $manager = \Drupal::service('plugin.manager.sendstate');
  $state = $manager->getState($message['to']);
  if (isset($state) && $state->isMute()) {
    $message['send'] = FALSE;
    drupal_set_message(t('Message to %mail suppressed.', array('%mail' => $message['to'])), 'warning');
  }
}
